In [27]:
import netCDF4 as nc
import numpy as np

In [35]:
nc_obj=nc.Dataset('global_ecmwf_det_wve_2018082112.nc')

In [36]:
nc_obj

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_64BIT_OFFSET data model, file format NETCDF3):
    Conventions: CF-1.6
    history: 2018-08-21 19:58:17 GMT by grib_to_netcdf-1.17.0: grib_to_netcdf -o W_NAFP_C_ECMF_20180821174245_P_C2P08211200082112001.swh.nc W_NAFP_C_ECMF_20180821174245_P_C2P08211200082112001.swh.grib
    nco_openmp_thread_number: 1
    dimensions(sizes): longitude(1440), latitude(721), time(41), record(1)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), int32 time(time), float64 swh(time,record,latitude,longitude)
    groups: 

查看变量的名字

In [37]:
nc_obj.variables.keys()

odict_keys(['longitude', 'latitude', 'time', 'swh'])

In [38]:
nc_obj.groups.values()

odict_values([])

In [40]:
nc_obj.variables['latitude'][:5]

masked_array(data = [ 90.    89.75  89.5   89.25  89.  ],
             mask = False,
       fill_value = 1e+20)

In [41]:
len(nc_obj.variables['longitude'][:])

1440

In [42]:
lng_index=np.where(nc_obj.variables['longitude'][:].data==0.25)

In [43]:
lat_index=np.where(nc_obj.variables['latitude'][:].data==79.0)

In [44]:
print(lng_index,lat_index)

(array([1]),) (array([44]),)


longitude 301，lat 181

In [45]:
nc_obj.variables['swh'][:].shape

(41, 1, 721, 1440)

In [52]:
nc_obj.variables['swh'][:1]

masked_array(data =
 [[[[-- -- -- ..., -- -- --]
   [-- -- -- ..., -- -- --]
   [-- -- -- ..., -- -- --]
   ..., 
   [-- -- -- ..., -- -- --]
   [-- -- -- ..., -- -- --]
   [-- -- -- ..., -- -- --]]]],
             mask =
 [[[[ True  True  True ...,  True  True  True]
   [ True  True  True ...,  True  True  True]
   [ True  True  True ...,  True  True  True]
   ..., 
   [ True  True  True ...,  True  True  True]
   [ True  True  True ...,  True  True  True]
   [ True  True  True ...,  True  True  True]]]],
       fill_value = -32767.0)

In [54]:
nc_obj.variables['time'][:]

masked_array(data = [1039956 1039962 1039968 1039974 1039980 1039986 1039992 1039998 1040004
 1040010 1040016 1040022 1040028 1040034 1040040 1040046 1040052 1040058
 1040064 1040070 1040076 1040082 1040088 1040094 1040100 1040106 1040112
 1040118 1040124 1040130 1040136 1040142 1040148 1040154 1040160 1040166
 1040172 1040178 1040184 1040190 1040196],
             mask = False,
       fill_value = 999999)

### 尝试读取swh的值

* 查看变量swh

In [94]:
nc_obj.variables['swh']

<class 'netCDF4._netCDF4.Variable'>
float64 swh(time, record, latitude, longitude)
    _FillValue: -32767.0
    missing_value: -32767
    units: m
    long_name: Significant height of combined wind waves and swell
unlimited dimensions: time
current shape = (41, 1, 721, 1440)
filling off

### 2.1 查看变量swh的第一组二位数组

In [96]:
nc_obj.variables['swh'].shape

(41, 1, 721, 1440)

In [98]:
nc_obj.variables['swh'][0].shape

(1, 721, 1440)

In [99]:
nc_obj.variables['swh'][0]

masked_array(data =
 [[[-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  ..., 
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]
  [-- -- -- ..., -- -- --]]],
             mask =
 [[[ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  ..., 
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]
  [ True  True  True ...,  True  True  True]]],
       fill_value = -32767.0)

### 2.2 最终的二维数组  
注意此二维数组，是第一个时间序列的二维数组

In [102]:
finial_arr=nc_obj.variables['swh'][0].data[0]

In [103]:
finial_arr

array([[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       ..., 
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
       [-32767., -32767., -32767., ..., -32767., -32767., -32767.]])

### 2.3 对二维数组进行检索

In [104]:
finial_arr[44,1]

1.9285667440051428

In [110]:
nc_obj.variables['swh'][0].data[0][44,1]

1.9285667440051428

----

### 使用列表推到的方式获取全时间序列的指定经纬度的值

In [117]:
nc_obj.variables['swh'][:].data[:2]

array([[[[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         ..., 
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.]]],


       [[[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         ..., 
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.]]]])

In [118]:
nc_obj.variables['swh'][:].data[:][44,1]

IndexError: index 44 is out of bounds for axis 0 with size 41

In [116]:
[print(temp) for temp in nc_obj.variables['swh'][:].data]

[[[-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  ..., 
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]]]
[[[-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  ..., 
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]]]
[[[-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  ..., 
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [-32767. -32767. -32767. ..., -32767. -32767. -32767.]
  [

[None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None,
 None]

In [119]:
[temp[0][44,1] for temp in nc_obj.variables['swh'][:].data]

[1.9285667440051428,
 1.5416455787619023,
 1.1749235280429984,
 1.0072262601724633,
 0.84467504600726429,
 0.69013887660651907,
 0.54748212459164147,
 0.47382835510266474,
 0.43992386568313968,
 0.47448566967564787,
 0.49802019361182648,
 0.65657933486940401,
 0.82719613229425715,
 1.0381534093186522,
 1.2214686610136614,
 1.413604432333909,
 1.3756046182199899,
 1.4269770122927516,
 1.6552845625792596,
 1.741015247084662,
 1.505835744021728,
 1.11970845745231,
 0.79851023875182747,
 0.62999045466767267,
 0.54967690166474004,
 0.54533182629827426,
 0.52567548967330957,
 0.50186174802192607,
 0.52879812060387543,
 0.78281376087298771,
 0.93344376157201392,
 1.0422546131786738,
 0.777149843441169,
 0.8467077486215997,
 1.0144103686641097,
 1.1546424124469761,
 1.123278947974816,
 1.1634488948239348,
 1.3035200271065519,
 1.4662530616173868,
 1.4777428469866414]

-------

In [69]:
nc_obj.variables['swh'][:1].data[0][0][0]

array([-32767., -32767., -32767., ..., -32767., -32767., -32767.])

In [74]:
nc_obj.variables['swh'][:1].data

array([[[[-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         ..., 
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.],
         [-32767., -32767., -32767., ..., -32767., -32767., -32767.]]]])

In [88]:
print(lng_index,lat_index)

(array([1]),) (array([44]),)


In [93]:
nc_obj.variables['swh'][:1].data[0][0][44][1]

1.9285667440051428

In [72]:
# nc_obj.variables['swh'][:][lng_index,lat_index].data

In [73]:
# nc_obj.variables['swh'][:][lat_index,lng_index].data