In [38]:
import netCDF4 as nc
import numpy as np

In [2]:
nc_obj=nc.Dataset('2018011420_08_24.nc')

In [3]:
nc_obj

<class 'netCDF4._netCDF4.Dataset'>
root group (NETCDF3_CLASSIC data model, file format NETCDF3):
    dimensions(sizes): latitude(181), longitude(301)
    variables(dimensions): float32 longitude(longitude), float32 latitude(latitude), float32 swh(latitude,longitude)
    groups: 

In [4]:
nc_obj.variables.keys()

odict_keys(['longitude', 'latitude', 'swh'])

In [5]:
nc_obj.groups.values()

odict_values([])

In [8]:
nc_obj.variables['latitude'][:5]

masked_array(data = [ 45.    44.75  44.5   44.25  44.  ],
             mask = False,
       fill_value = 1e+20)

In [17]:
len(nc_obj.variables['longitude'][:])

301

注意ndarray使用bool索引的方式索引

In [36]:
type(nc_obj.variables['longitude'][:].data)

numpy.ndarray

In [40]:
nc_obj.variables['longitude'][:].data

array([  90.  ,   90.25,   90.5 ,   90.75,   91.  ,   91.25,   91.5 ,
         91.75,   92.  ,   92.25,   92.5 ,   92.75,   93.  ,   93.25,
         93.5 ,   93.75,   94.  ,   94.25,   94.5 ,   94.75,   95.  ,
         95.25,   95.5 ,   95.75,   96.  ,   96.25,   96.5 ,   96.75,
         97.  ,   97.25,   97.5 ,   97.75,   98.  ,   98.25,   98.5 ,
         98.75,   99.  ,   99.25,   99.5 ,   99.75,  100.  ,  100.25,
        100.5 ,  100.75,  101.  ,  101.25,  101.5 ,  101.75,  102.  ,
        102.25,  102.5 ,  102.75,  103.  ,  103.25,  103.5 ,  103.75,
        104.  ,  104.25,  104.5 ,  104.75,  105.  ,  105.25,  105.5 ,
        105.75,  106.  ,  106.25,  106.5 ,  106.75,  107.  ,  107.25,
        107.5 ,  107.75,  108.  ,  108.25,  108.5 ,  108.75,  109.  ,
        109.25,  109.5 ,  109.75,  110.  ,  110.25,  110.5 ,  110.75,
        111.  ,  111.25,  111.5 ,  111.75,  112.  ,  112.25,  112.5 ,
        112.75,  113.  ,  113.25,  113.5 ,  113.75,  114.  ,  114.25,
        114.5 ,  114

In [49]:
lng_index=np.where(nc_obj.variables['longitude'][:].data==120.25)

In [50]:
lat_index=np.where(nc_obj.variables['latitude'][:].data==44.75)

In [51]:
print(lng_index,lat_index)

(array([121]),) (array([1]),)


In [15]:
len(nc_obj.variables['latitude'][:])

181

In [16]:
len(nc_obj.variables['swh'][:])

181

longitude 301，lat 181

In [55]:
nc_obj.variables['swh'][:].shape

(181, 301)

In [52]:
nc_obj.variables['swh'][:]

masked_array(data =
 [[ 0.          0.          0.         ...,  3.79013753  3.81374502
   3.8166697 ]
 [ 0.          0.          0.         ...,  3.73289442  3.75065231
   3.74542928]
 [ 0.          0.          0.         ...,  3.67314434  3.68170977
   3.67606902]
 ..., 
 [ 1.29114306  1.28890967  1.2940464  ...,  2.2034173   2.20362639
   2.18628621]
 [ 1.29382312  1.29627979  1.30074644 ...,  2.14304066  2.13322163
   2.14304066]
 [ 1.30342638  1.30744648  1.31369984 ...,  2.07950878  2.06782269
   2.07869434]],
             mask =
 False,
       fill_value = 1e+20)

** 注意python中只有1是true，其他均为false**  
## 取值方法1：

In [57]:
nc_obj.variables['swh'][:][lng_index,lat_index]

masked_array(data =
 [[ 1.012869]],
             mask =
 False,
       fill_value = 1e+20)

In [58]:
nc_obj.variables['swh'][:][lng_index,lat_index].data

array([[ 1.012869]], dtype=float32)

## 取值方法2：

In [63]:
lng_max=max(nc_obj.variables['longitude'][:].data)

In [64]:
lng_min=min(nc_obj.variables['longitude'][:].data)

In [69]:
print(lng_max,lng_min)

165.0 90.0


In [67]:
int((120.25-lng_min)/0.25+1)

122

In [26]:
nc_obj.variables['swh'][:].data

array([[ 0.        ,  0.        ,  0.        , ...,  3.79013753,
         3.81374502,  3.8166697 ],
       [ 0.        ,  0.        ,  0.        , ...,  3.73289442,
         3.75065231,  3.74542928],
       [ 0.        ,  0.        ,  0.        , ...,  3.67314434,
         3.68170977,  3.67606902],
       ..., 
       [ 1.29114306,  1.28890967,  1.2940464 , ...,  2.2034173 ,
         2.20362639,  2.18628621],
       [ 1.29382312,  1.29627979,  1.30074644, ...,  2.14304066,
         2.13322163,  2.14304066],
       [ 1.30342638,  1.30744648,  1.31369984, ...,  2.07950878,
         2.06782269,  2.07869434]], dtype=float32)

In [30]:
# print(nc_obj.variables['swh'][:].data)

In [28]:
nc_obj.variables['swh'][:].fill_value

1e+20

In [22]:
nc_obj.variables['latitude'][:]

masked_array(data = [ 45.    44.75  44.5   44.25  44.    43.75  43.5   43.25  43.    42.75
  42.5   42.25  42.    41.75  41.5   41.25  41.    40.75  40.5   40.25  40.
  39.75  39.5   39.25  39.    38.75  38.5   38.25  38.    37.75  37.5
  37.25  37.    36.75  36.5   36.25  36.    35.75  35.5   35.25  35.    34.75
  34.5   34.25  34.    33.75  33.5   33.25  33.    32.75  32.5   32.25  32.
  31.75  31.5   31.25  31.    30.75  30.5   30.25  30.    29.75  29.5
  29.25  29.    28.75  28.5   28.25  28.    27.75  27.5   27.25  27.    26.75
  26.5   26.25  26.    25.75  25.5   25.25  25.    24.75  24.5   24.25  24.
  23.75  23.5   23.25  23.    22.75  22.5   22.25  22.    21.75  21.5
  21.25  21.    20.75  20.5   20.25  20.    19.75  19.5   19.25  19.    18.75
  18.5   18.25  18.    17.75  17.5   17.25  17.    16.75  16.5   16.25  16.
  15.75  15.5   15.25  15.    14.75  14.5   14.25  14.    13.75  13.5
  13.25  13.    12.75  12.5   12.25  12.    11.75  11.5   11.25  11.    10.75
  10.5   10.2